channels:
  - conda-forge
dependencies:
  - r-base>=4
  - r-irkernel>=1.1
  - clang
  - openmp
  - llvm-openmp
  - libgomp
  - r-mvtnorm
  - r-quantreg
  - r-mcmcpack
  - r-mnormt
  - r-randtoolbox
  - r-rcpparmadillo
  - r-rcppeigen
