channels:
  - conda-forge
dependencies:
  - r-base>=4
  - r-irkernel>=1.1
  - gxx_linux-64
  - openmp
  - libgomp
  - r-mvtnorm
  - r-quantreg
  - r-zoo
  - r-sandwich
  - r-mcmcpack
  - r-mnormt
  - r-randtoolbox
  - r-rcpparmadillo
  - r-rcppeigen
